### ISSUE TITLE
Maze Theme - October 2020

### ISSUE THREAD

**Issue by gaurang2001** [tedxnitksurathkal/tedxnitksurathkal.github.io#98]
## The Theme - Traiblazers
Have an immersive theme reveal using A-Frame. Implement in the form of a maze, where the user should be able to navigate his/her way through a maze and reach the final destination, that is where the theme would be revealed.

## Tasks
- [x] Maze using Aframe
- [x] Text Animation for final reveal
- [ ] Modal with instructions
